title: Minimal theme
logo: /assets/logo.jpg
description: Scrape data from a specified URL. The extracted data can be saved in CSV or Excel format, and users can also download images directly.
theme: jekyll-theme-minimal
